language: rust
os:
    - linux
before_script:
    - rustup default nightly
    - rustup component add rustfmt-preview
script:
    - cargo fmt --version
    - cargo fmt --all -- --write-mode=diff
    - cargo build --verbose
    - cargo test --verbose
