language: rust
os:
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow-failures:
    - rust: nightly
before_script:
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly
script:
  - cargo +nightly fmt --version
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
