language: rust
os:
    - linux
before_script:
    - rustup toolchain install nightly
    - rustup component add --toolchain nightly rustfmt-preview
    - which rustfmt || cargo install --force rustfmt-nightly
script:
    - cargo fmt --version
    - cargo +nightly fmt --all -- --write-mode=diff
    - cargo build --verbose
    - cargo test --verbose
